import { iconData } from './iconConfig';

type IconTemplateProps = { componentName: string; data: string };

export const iconTemplate = ({
	componentName,
	data,
}: IconTemplateProps): string => {
	const render = `
// GENERATED BY ./scripts/iconScript.ts

import { IconProps, flipFunction } from '../flipFunction';

export const ${componentName} = ({
	title,
	width = "${iconData.iconDefault.width}",
	height = "${iconData.iconDefault.height}",
	color = "${iconData.iconDefault.color}",
	rotate = ${iconData.iconDefault.rotate},
	horizontalFlip = ${iconData.iconDefault.horizontalFlip},
	verticalFlip = ${iconData.iconDefault.verticalFlip}}: IconProps):JSX.Element => {
    const { scaleX, scaleY, translateX, translateY } = flipFunction({horizontalFlip,verticalFlip})
return (
    ${data}
    );
};

`;
	return render;
};
