// GENERATED BY ./scripts/storyBookScript.ts
import React from 'react';
import { ComponentStory, ComponentMeta } from '@storybook/react';
import { BeMindfulUntapped } from './BeMindfulUntapped';

export default {
	title: 'Design System/icons/BeMindfulUntapped',
	component: BeMindfulUntapped,
	argTypes: {
		color: { control: 'color' },
		rotate: { control: 'number' },
		width: {
			control: { type: 'number' },
		},
		height: {
			control: { type: 'number' },
		},
	},
} as ComponentMeta<typeof BeMindfulUntapped>;

export const Default: ComponentStory<typeof BeMindfulUntapped> = (args) => (
	<BeMindfulUntapped {...args} />
);
