// GENERATED BY ./scripts/storyBookScript.ts
import React from 'react';
import { ComponentStory, ComponentMeta } from '@storybook/react';
import { MoveEveryDayTapped } from './MoveEveryDayTapped';

export default {
	title: 'Design System/icons/MoveEveryDayTapped',
	component: MoveEveryDayTapped,
	argTypes: {
		color: { control: 'color' },
		rotate: { control: 'number' },
		width: {
			control: { type: 'number' },
		},
		height: {
			control: { type: 'number' },
		},
	},
} as ComponentMeta<typeof MoveEveryDayTapped>;

export const Default: ComponentStory<typeof MoveEveryDayTapped> = (args) => (
	<MoveEveryDayTapped {...args} />
);
