// GENERATED BY ./scripts/storyBookScript.ts
import React from 'react';
import { ComponentStory, ComponentMeta } from '@storybook/react';
import { NoDataUser } from './NoDataUser';

export default {
	title: 'Design System/icons/NoDataUser',
	component: NoDataUser,
	argTypes: {
		color: { control: 'color' },
		rotate: { control: 'number' },
		width: {
			control: { type: 'number' },
		},
		height: {
			control: { type: 'number' },
		},
	},
} as ComponentMeta<typeof NoDataUser>;

export const Default: ComponentStory<typeof NoDataUser> = (args) => (
	<NoDataUser {...args} />
);
