// GENERATED BY ./scripts/storyBookScript.ts
import React from 'react';
import { ComponentStory, ComponentMeta } from '@storybook/react';
import { AddUser } from './AddUser';

export default {
	title: 'Design System/icons/AddUser',
	component: AddUser,
	argTypes: {
		color: { control: 'color' },
		rotate: { control: 'number' },
		width: {
			control: { type: 'number' },
		},
		height: {
			control: { type: 'number' },
		},
	},
} as ComponentMeta<typeof AddUser>;

export const Default: ComponentStory<typeof AddUser> = (args) => (
	<AddUser {...args} />
);
