// GENERATED BY ./scripts/storyBookScript.ts
import React from 'react';
import { ComponentStory, ComponentMeta } from '@storybook/react';
import { AddUserSolid } from './AddUserSolid';

export default {
	title: 'Design System/icons/AddUserSolid',
	component: AddUserSolid,
	argTypes: {
		color: { control: 'color' },
		rotate: { control: 'number' },
		width: {
			control: { type: 'number' },
		},
		height: {
			control: { type: 'number' },
		},
	},
} as ComponentMeta<typeof AddUserSolid>;

export const Default: ComponentStory<typeof AddUserSolid> = (args) => (
	<AddUserSolid {...args} />
);
