// GENERATED BY ./scripts/storyBookScript.ts
import React from 'react';
import { ComponentStory, ComponentMeta } from '@storybook/react';
import { AddOutlined } from './AddOutlined';

export default {
	title: 'Design System/icons/AddOutlined',
	component: AddOutlined,
	argTypes: {
		color: { control: 'color' },
		rotate: { control: 'number' },
		width: {
			control: { type: 'number' },
		},
		height: {
			control: { type: 'number' },
		},
	},
} as ComponentMeta<typeof AddOutlined>;

export const Default: ComponentStory<typeof AddOutlined> = (args) => (
	<AddOutlined {...args} />
);
