// GENERATED BY ./scripts/storyBookScript.ts
import React from 'react';
import { ComponentStory, ComponentMeta } from '@storybook/react';
import { MagnifyingGlass } from './MagnifyingGlass';

export default {
	title: 'Design System/icons/MagnifyingGlass',
	component: MagnifyingGlass,
	argTypes: {
		color: { control: 'color' },
		rotate: { control: 'number' },
		width: {
			control: { type: 'number' },
		},
		height: {
			control: { type: 'number' },
		},
	},
} as ComponentMeta<typeof MagnifyingGlass>;

export const Default: ComponentStory<typeof MagnifyingGlass> = (args) => (
	<MagnifyingGlass {...args} />
);
