// GENERATED BY ./scripts/storyBookScript.ts
import React from 'react';
import { ComponentStory, ComponentMeta } from '@storybook/react';
import { LearnSomethingNewLHQ } from './LearnSomethingNewLHQ';

export default {
	title: 'Design System/icons/LearnSomethingNewLHQ',
	component: LearnSomethingNewLHQ,
	argTypes: {
		color: { control: 'color' },
		rotate: { control: 'number' },
		width: {
			control: { type: 'number' },
		},
		height: {
			control: { type: 'number' },
		},
	},
} as ComponentMeta<typeof LearnSomethingNewLHQ>;

export const Default: ComponentStory<typeof LearnSomethingNewLHQ> = (args) => (
	<LearnSomethingNewLHQ {...args} />
);
