// GENERATED BY ./scripts/storyBookScript.ts
import React from 'react';
import { ComponentStory, ComponentMeta } from '@storybook/react';
import { InfoOutlined } from './InfoOutlined';

export default {
	title: 'Design System/icons/InfoOutlined',
	component: InfoOutlined,
	argTypes: {
		color: { control: 'color' },
		rotate: { control: 'number' },
		width: {
			control: { type: 'number' },
		},
		height: {
			control: { type: 'number' },
		},
	},
} as ComponentMeta<typeof InfoOutlined>;

export const Default: ComponentStory<typeof InfoOutlined> = (args) => (
	<InfoOutlined {...args} />
);
