// GENERATED BY ./scripts/storyBookScript.ts
import React from 'react';
import { ComponentStory, ComponentMeta } from '@storybook/react';
import { CheckboxEmpty } from './CheckboxEmpty';

export default {
	title: 'Design System/icons/CheckboxEmpty',
	component: CheckboxEmpty,
	argTypes: {
		color: { control: 'color' },
		rotate: { control: 'number' },
		width: {
			control: { type: 'number' },
		},
		height: {
			control: { type: 'number' },
		},
	},
} as ComponentMeta<typeof CheckboxEmpty>;

export const Default: ComponentStory<typeof CheckboxEmpty> = (args) => (
	<CheckboxEmpty {...args} />
);
