// GENERATED BY ./scripts/storyBookScript.ts
import React from 'react';
import { ComponentStory, ComponentMeta } from '@storybook/react';
import { TraditionalArrowDown } from './TraditionalArrowDown';

export default {
	title: 'Design System/icons/TraditionalArrowDown',
	component: TraditionalArrowDown,
	argTypes: {
		color: { control: 'color' },
		rotate: { control: 'number' },
		width: {
			control: { type: 'number' },
		},
		height: {
			control: { type: 'number' },
		},
	},
} as ComponentMeta<typeof TraditionalArrowDown>;

export const Default: ComponentStory<typeof TraditionalArrowDown> = (args) => (
	<TraditionalArrowDown {...args} />
);
