// GENERATED BY ./scripts/storyBookScript.ts
import React from 'react';
import { ComponentStory, ComponentMeta } from '@storybook/react';
import { RemoveUserSolid } from './RemoveUserSolid';

export default {
	title: 'Design System/icons/RemoveUserSolid',
	component: RemoveUserSolid,
	argTypes: {
		color: { control: 'color' },
		rotate: { control: 'number' },
		width: {
			control: { type: 'number' },
		},
		height: {
			control: { type: 'number' },
		},
	},
} as ComponentMeta<typeof RemoveUserSolid>;

export const Default: ComponentStory<typeof RemoveUserSolid> = (args) => (
	<RemoveUserSolid {...args} />
);
