// GENERATED BY ./scripts/storyBookScript.ts
import React from 'react';
import { ComponentStory, ComponentMeta } from '@storybook/react';
import { GetGoodRestLHQ } from './GetGoodRestLHQ';

export default {
	title: 'Design System/icons/GetGoodRestLHQ',
	component: GetGoodRestLHQ,
	argTypes: {
		color: { control: 'color' },
		rotate: { control: 'number' },
		width: {
			control: { type: 'number' },
		},
		height: {
			control: { type: 'number' },
		},
	},
} as ComponentMeta<typeof GetGoodRestLHQ>;

export const Default: ComponentStory<typeof GetGoodRestLHQ> = (args) => (
	<GetGoodRestLHQ {...args} />
);
