// GENERATED BY ./scripts/storyBookScript.ts
import React from 'react';
import { ComponentStory, ComponentMeta } from '@storybook/react';
import { BuildYourVillageLHQ } from './BuildYourVillageLHQ';

export default {
	title: 'Design System/icons/BuildYourVillageLHQ',
	component: BuildYourVillageLHQ,
	argTypes: {
		color: { control: 'color' },
		rotate: { control: 'number' },
		width: {
			control: { type: 'number' },
		},
		height: {
			control: { type: 'number' },
		},
	},
} as ComponentMeta<typeof BuildYourVillageLHQ>;

export const Default: ComponentStory<typeof BuildYourVillageLHQ> = (args) => (
	<BuildYourVillageLHQ {...args} />
);
