// GENERATED BY ./scripts/storyBookScript.ts
import React from 'react';
import { ComponentStory, ComponentMeta } from '@storybook/react';
import { ArrowRight } from './ArrowRight';

export default {
	title: 'Design System/icons/ArrowRight',
	component: ArrowRight,
	argTypes: {
		color: { control: 'color' },
		rotate: { control: 'number' },
		width: {
			control: { type: 'number' },
		},
		height: {
			control: { type: 'number' },
		},
	},
} as ComponentMeta<typeof ArrowRight>;

export const Default: ComponentStory<typeof ArrowRight> = (args) => (
	<ArrowRight {...args} />
);
