// GENERATED BY ./scripts/storyBookScript.ts
import React from 'react';
import { ComponentStory, ComponentMeta } from '@storybook/react';
import { StayTrueToPurposeLHQ } from './StayTrueToPurposeLHQ';

export default {
	title: 'Design System/icons/StayTrueToPurposeLHQ',
	component: StayTrueToPurposeLHQ,
	argTypes: {
		color: { control: 'color' },
		rotate: { control: 'number' },
		width: {
			control: { type: 'number' },
		},
		height: {
			control: { type: 'number' },
		},
	},
} as ComponentMeta<typeof StayTrueToPurposeLHQ>;

export const Default: ComponentStory<typeof StayTrueToPurposeLHQ> = (args) => (
	<StayTrueToPurposeLHQ {...args} />
);
