// GENERATED BY ./scripts/storyBookScript.ts
import React from 'react';
import { ComponentStory, ComponentMeta } from '@storybook/react';
import { Home } from './Home';

export default {
	title: 'Design System/icons/Home',
	component: Home,
	argTypes: {
		color: { control: 'color' },
		rotate: { control: 'number' },
		width: {
			control: { type: 'number' },
		},
		height: {
			control: { type: 'number' },
		},
	},
} as ComponentMeta<typeof Home>;

export const Default: ComponentStory<typeof Home> = (args) => (
	<Home {...args} />
);
