// GENERATED BY ./scripts/storyBookScript.ts
import React from 'react';
import { ComponentStory, ComponentMeta } from '@storybook/react';
import { Configure } from './Configure';

export default {
	title: 'Design System/icons/Configure',
	component: Configure,
	argTypes: {
		color: { control: 'color' },
		rotate: { control: 'number' },
		width: {
			control: { type: 'number' },
		},
		height: {
			control: { type: 'number' },
		},
	},
} as ComponentMeta<typeof Configure>;

export const Default: ComponentStory<typeof Configure> = (args) => (
	<Configure {...args} />
);
