// GENERATED BY ./scripts/storyBookScript.ts
import React from 'react';
import { ComponentStory, ComponentMeta } from '@storybook/react';
import { Test } from './Test';

export default {
	title: 'Design System/icons/Test',
	component: Test,
	argTypes: {
		color: { control: 'color' },
		rotate: { control: 'number' },
		width: {
			control: { type: 'number' },
		},
		height: {
			control: { type: 'number' },
		},
	},
} as ComponentMeta<typeof Test>;

export const Default: ComponentStory<typeof Test> = (args) => (
	<Test {...args} />
);
