// GENERATED BY ./scripts/storyBookScript.ts
import React from 'react';
import { ComponentStory, ComponentMeta } from '@storybook/react';
import { GetGoodRestUntapped } from './GetGoodRestUntapped';

export default {
	title: 'Design System/icons/GetGoodRestUntapped',
	component: GetGoodRestUntapped,
	argTypes: {
		color: { control: 'color' },
		rotate: { control: 'number' },
		width: {
			control: { type: 'number' },
		},
		height: {
			control: { type: 'number' },
		},
	},
} as ComponentMeta<typeof GetGoodRestUntapped>;

export const Default: ComponentStory<typeof GetGoodRestUntapped> = (args) => (
	<GetGoodRestUntapped {...args} />
);
