// GENERATED BY ./scripts/storyBookScript.ts
import React from 'react';
import { ComponentStory, ComponentMeta } from '@storybook/react';
import { EmptyClipboardSearch } from './EmptyClipboardSearch';

export default {
	title: 'Design System/icons/EmptyClipboardSearch',
	component: EmptyClipboardSearch,
	argTypes: {
		color: { control: 'color' },
		rotate: { control: 'number' },
		width: {
			control: { type: 'number' },
		},
		height: {
			control: { type: 'number' },
		},
	},
} as ComponentMeta<typeof EmptyClipboardSearch>;

export const Default: ComponentStory<typeof EmptyClipboardSearch> = (args) => (
	<EmptyClipboardSearch {...args} />
);
