// GENERATED BY ./scripts/storyBookScript.ts
import React from 'react';
import { ComponentStory, ComponentMeta } from '@storybook/react';
import { Kebab } from './Kebab';

export default {
	title: 'Design System/icons/Kebab',
	component: Kebab,
	argTypes: {
		color: { control: 'color' },
		rotate: { control: 'number' },
		width: {
			control: { type: 'number' },
		},
		height: {
			control: { type: 'number' },
		},
	},
} as ComponentMeta<typeof Kebab>;

export const Default: ComponentStory<typeof Kebab> = (args) => (
	<Kebab {...args} />
);
