// GENERATED BY ./scripts/storyBookScript.ts
import React from 'react';
import { ComponentStory, ComponentMeta } from '@storybook/react';
import { NonModifiableRiskFactorLHQ } from './NonModifiableRiskFactorLHQ';

export default {
	title: 'Design System/icons/NonModifiableRiskFactorLHQ',
	component: NonModifiableRiskFactorLHQ,
	argTypes: {
		color: { control: 'color' },
		rotate: { control: 'number' },
		width: {
			control: { type: 'number' },
		},
		height: {
			control: { type: 'number' },
		},
	},
} as ComponentMeta<typeof NonModifiableRiskFactorLHQ>;

export const Default: ComponentStory<typeof NonModifiableRiskFactorLHQ> = (
	args
) => <NonModifiableRiskFactorLHQ {...args} />;
