// GENERATED BY ./scripts/storyBookScript.ts
import React from 'react';
import { ComponentStory, ComponentMeta } from '@storybook/react';
import { ArrowCircleLeft } from './ArrowCircleLeft';

export default {
	title: 'Design System/icons/ArrowCircleLeft',
	component: ArrowCircleLeft,
	argTypes: {
		color: { control: 'color' },
		rotate: { control: 'number' },
		width: {
			control: { type: 'number' },
		},
		height: {
			control: { type: 'number' },
		},
	},
} as ComponentMeta<typeof ArrowCircleLeft>;

export const Default: ComponentStory<typeof ArrowCircleLeft> = (args) => (
	<ArrowCircleLeft {...args} />
);
