// GENERATED BY ./scripts/storyBookScript.ts
import React from 'react';
import { ComponentStory, ComponentMeta } from '@storybook/react';
import { LogoStacked } from './LogoStacked';

export default {
	title: 'Design System/icons/LogoStacked',
	component: LogoStacked,
	argTypes: {
		color: { control: 'color' },
		rotate: { control: 'number' },
		width: {
			control: { type: 'number' },
		},
		height: {
			control: { type: 'number' },
		},
	},
} as ComponentMeta<typeof LogoStacked>;

export const Default: ComponentStory<typeof LogoStacked> = (args) => (
	<LogoStacked {...args} />
);
