// GENERATED BY ./scripts/storyBookScript.ts
import React from 'react';
import { ComponentStory, ComponentMeta } from '@storybook/react';
import { BuildYourVillageUntapped } from './BuildYourVillageUntapped';

export default {
	title: 'Design System/icons/BuildYourVillageUntapped',
	component: BuildYourVillageUntapped,
	argTypes: {
		color: { control: 'color' },
		rotate: { control: 'number' },
		width: {
			control: { type: 'number' },
		},
		height: {
			control: { type: 'number' },
		},
	},
} as ComponentMeta<typeof BuildYourVillageUntapped>;

export const Default: ComponentStory<typeof BuildYourVillageUntapped> = (
	args
) => <BuildYourVillageUntapped {...args} />;
