// GENERATED BY ./scripts/storyBookScript.ts
import React from 'react';
import { ComponentStory, ComponentMeta } from '@storybook/react';
import { HeartShapedPersonOutlined } from './HeartShapedPersonOutlined';

export default {
	title: 'Design System/icons/HeartShapedPersonOutlined',
	component: HeartShapedPersonOutlined,
	argTypes: {
		color: { control: 'color' },
		rotate: { control: 'number' },
		width: {
			control: { type: 'number' },
		},
		height: {
			control: { type: 'number' },
		},
	},
} as ComponentMeta<typeof HeartShapedPersonOutlined>;

export const Default: ComponentStory<typeof HeartShapedPersonOutlined> = (
	args
) => <HeartShapedPersonOutlined {...args} />;
