// GENERATED BY ./scripts/storyBookScript.ts
import React from 'react';
import { ComponentStory, ComponentMeta } from '@storybook/react';
import { Download } from './Download';

export default {
	title: 'Design System/icons/Download',
	component: Download,
	argTypes: {
		color: { control: 'color' },
		rotate: { control: 'number' },
		width: {
			control: { type: 'number' },
		},
		height: {
			control: { type: 'number' },
		},
	},
} as ComponentMeta<typeof Download>;

export const Default: ComponentStory<typeof Download> = (args) => (
	<Download {...args} />
);
