// GENERATED BY ./scripts/storyBookScript.ts
import React from 'react';
import { ComponentStory, ComponentMeta } from '@storybook/react';
import { BrainCenterDotOutlined } from './BrainCenterDotOutlined';

export default {
	title: 'Design System/icons/BrainCenterDotOutlined',
	component: BrainCenterDotOutlined,
	argTypes: {
		color: { control: 'color' },
		rotate: { control: 'number' },
		width: {
			control: { type: 'number' },
		},
		height: {
			control: { type: 'number' },
		},
	},
} as ComponentMeta<typeof BrainCenterDotOutlined>;

export const Default: ComponentStory<typeof BrainCenterDotOutlined> = (
	args
) => <BrainCenterDotOutlined {...args} />;
