// GENERATED BY ./scripts/storyBookScript.ts
import React from 'react';
import { ComponentStory, ComponentMeta } from '@storybook/react';
import { Frailty } from './Frailty';

export default {
	title: 'Design System/icons/Frailty',
	component: Frailty,
	argTypes: {
		color: { control: 'color' },
		rotate: { control: 'number' },
		width: {
			control: { type: 'number' },
		},
		height: {
			control: { type: 'number' },
		},
	},
} as ComponentMeta<typeof Frailty>;

export const Default: ComponentStory<typeof Frailty> = (args) => (
	<Frailty {...args} />
);
