// GENERATED BY ./scripts/storyBookScript.ts
import React from 'react';
import { ComponentStory, ComponentMeta } from '@storybook/react';
import { AddUserOutlined } from './AddUserOutlined';

export default {
	title: 'Design System/icons/AddUserOutlined',
	component: AddUserOutlined,
	argTypes: {
		color: { control: 'color' },
		rotate: { control: 'number' },
		width: {
			control: { type: 'number' },
		},
		height: {
			control: { type: 'number' },
		},
	},
} as ComponentMeta<typeof AddUserOutlined>;

export const Default: ComponentStory<typeof AddUserOutlined> = (args) => (
	<AddUserOutlined {...args} />
);
