// GENERATED BY ./scripts/storyBookScript.ts
import React from 'react';
import { ComponentStory, ComponentMeta } from '@storybook/react';
import { AddSolid } from './AddSolid';

export default {
	title: 'Design System/icons/AddSolid',
	component: AddSolid,
	argTypes: {
		color: { control: 'color' },
		rotate: { control: 'number' },
		width: {
			control: { type: 'number' },
		},
		height: {
			control: { type: 'number' },
		},
	},
} as ComponentMeta<typeof AddSolid>;

export const Default: ComponentStory<typeof AddSolid> = (args) => (
	<AddSolid {...args} />
);
