// GENERATED BY ./scripts/iconScript.ts

import { IconProps, flipFunction } from '../flipFunction';

export const MoveEveryDayUntapped = ({
	title,
	width = '24',
	height = '24',
	color = '#676671',
	rotate = 0,
	horizontalFlip = false,
	verticalFlip = false,
}: IconProps): JSX.Element => {
	const { scaleX, scaleY, translateX, translateY } = flipFunction({
		horizontalFlip,
		verticalFlip,
	});
	return (
		<svg
			viewBox='0 0 36 36'
			xmlns='http://www.w3.org/2000/svg'
			data-testid='MoveEveryDayUntapped-svg-component'
			transform={`rotate(${rotate}) translate(${translateX}, ${translateY}) scale(${scaleX}, ${scaleY})`}
			fill={color}
			width={width}
			height={height}>
			<title>{title || 'MoveEveryDayUntapped'}</title>
			<rect
				x='1.25'
				y='1.25'
				width='33.5'
				height='33.5'
				rx='16.75'
				fill='#F2F1F3'
			/>
			<path
				fillRule='evenodd'
				clipRule='evenodd'
				d='M21.931 20.3854C21.6876 18.8014 20.3153 15.045 20.3153 15.045L22.8793 8.40744C23.0851 7.87502 22.8203 7.2755 22.2872 7.06976C21.7562 6.86401 21.1552 7.12875 20.9495 7.66191C20.9495 7.66191 18.7969 12.9898 18.6281 13.0399C18.2712 13.1461 17.6303 13.3474 17.1031 13.5783C15.6186 14.2309 12.8083 15.2736 12.8083 15.2736C12.4868 15.3473 12.2191 15.5678 12.0879 15.8687C11.9551 16.1703 11.9736 16.5154 12.138 16.8008L13.9985 20.0344C14.1902 20.367 14.5391 20.5528 14.896 20.5528C15.0715 20.5528 15.2485 20.5078 15.4114 20.4142C15.907 20.1288 16.0773 19.4953 15.7919 18.9998L14.6312 16.9852L15.8384 16.7116L17.3265 20.5078L14.6983 27.5524C14.4697 28.0767 14.7116 28.6859 15.2359 28.9137C15.3701 28.9727 15.5095 29 15.6467 29C16.0471 29 16.4283 28.7662 16.5972 28.3761L19.541 21.7769L20.8905 28.1217C20.9701 28.6342 21.4089 29 21.9118 29C21.9649 29 22.0173 28.9956 22.0704 28.9867C22.6352 28.8997 23.0224 28.3717 22.9361 27.8068C22.9361 27.8068 22.1743 21.9679 21.931 20.3854ZM17.9835 10.9486C17.9835 12.0478 17.0925 12.9389 15.9932 12.9389C14.894 12.9389 14.0029 12.0478 14.0029 10.9486C14.0029 9.84938 14.894 8.95829 15.9932 8.95829C17.0925 8.95829 17.9835 9.84938 17.9835 10.9486Z'
				fill='#676671'
			/>
			<circle
				cx='18'
				cy='18'
				r='16.75'
				fill='none'
				stroke='#DDA700'
				stroke-width='1.5'
				stroke-dasharray='3 4'
			/>
		</svg>
	);
};
