// GENERATED BY ./scripts/storyBookScript.ts
import React from 'react';
import { ComponentStory, ComponentMeta } from '@storybook/react';
import { MoveEveryDayUntapped } from './MoveEveryDayUntapped';

export default {
	title: 'Design System/icons/MoveEveryDayUntapped',
	component: MoveEveryDayUntapped,
	argTypes: {
		color: { control: 'color' },
		rotate: { control: 'number' },
		width: {
			control: { type: 'number' },
		},
		height: {
			control: { type: 'number' },
		},
	},
} as ComponentMeta<typeof MoveEveryDayUntapped>;

export const Default: ComponentStory<typeof MoveEveryDayUntapped> = (args) => (
	<MoveEveryDayUntapped {...args} />
);
