// GENERATED BY ./scripts/storyBookScript.ts
import React from 'react';
import { ComponentStory, ComponentMeta } from '@storybook/react';
import { TraditionalArrowUp } from './TraditionalArrowUp';

export default {
	title: 'Design System/icons/TraditionalArrowUp',
	component: TraditionalArrowUp,
	argTypes: {
		color: { control: 'color' },
		rotate: { control: 'number' },
		width: {
			control: { type: 'number' },
		},
		height: {
			control: { type: 'number' },
		},
	},
} as ComponentMeta<typeof TraditionalArrowUp>;

export const Default: ComponentStory<typeof TraditionalArrowUp> = (args) => (
	<TraditionalArrowUp {...args} />
);
