// GENERATED BY ./scripts/storyBookScript.ts
import React from 'react';
import { ComponentStory, ComponentMeta } from '@storybook/react';
import { EyeClosedOutlined } from './EyeClosedOutlined';

export default {
	title: 'Design System/icons/EyeClosedOutlined',
	component: EyeClosedOutlined,
	argTypes: {
		color: { control: 'color' },
		rotate: { control: 'number' },
		width: {
			control: { type: 'number' },
		},
		height: {
			control: { type: 'number' },
		},
	},
} as ComponentMeta<typeof EyeClosedOutlined>;

export const Default: ComponentStory<typeof EyeClosedOutlined> = (args) => (
	<EyeClosedOutlined {...args} />
);
