// GENERATED BY ./scripts/storyBookScript.ts
import React from 'react';
import { ComponentStory, ComponentMeta } from '@storybook/react';
import { ArrowIncrease } from './ArrowIncrease';

export default {
	title: 'Design System/icons/ArrowIncrease',
	component: ArrowIncrease,
	argTypes: {
		color: { control: 'color' },
		rotate: { control: 'number' },
		width: {
			control: { type: 'number' },
		},
		height: {
			control: { type: 'number' },
		},
	},
} as ComponentMeta<typeof ArrowIncrease>;

export const Default: ComponentStory<typeof ArrowIncrease> = (args) => (
	<ArrowIncrease {...args} />
);
