// GENERATED BY ./scripts/iconScript.ts

import { IconProps, flipFunction } from '../flipFunction';

export const ArrowIncrease = ({
	title,
	width = '24',
	height = '24',
	color = '#676671',
	rotate = 0,
	horizontalFlip = false,
	verticalFlip = false,
}: IconProps): JSX.Element => {
	const { scaleX, scaleY, translateX, translateY } = flipFunction({
		horizontalFlip,
		verticalFlip,
	});
	return (
		<svg
			viewBox='0 0 19 12'
			xmlns='http://www.w3.org/2000/svg'
			data-testid='ArrowIncrease-svg-component'
			transform={`rotate(${rotate}) translate(${translateX}, ${translateY}) scale(${scaleX}, ${scaleY})`}
			fill={color}
			width={width}
			height={height}>
			<title>{title || 'ArrowIncrease'}</title>

			<path
				d='M17.167 11.3334C17.5715 11.3334 17.9361 11.0735 18.0909 10.6749C18.2457 10.2764 18.1601 9.81757 17.8741 9.5125L9.87413 0.979168C9.48361 0.562608 8.85044 0.562608 8.45992 0.979167L0.459915 9.5125C0.173917 9.81756 0.0883607 10.2764 0.243142 10.6749C0.397922 11.0735 0.762559 11.3334 1.16702 11.3334L17.167 11.3334Z'
				fill='current'
			/>
		</svg>
	);
};
