// GENERATED BY ./scripts/storyBookScript.ts
import React from 'react';
import { ComponentStory, ComponentMeta } from '@storybook/react';
import { LearnSomethingNewUntapped } from './LearnSomethingNewUntapped';

export default {
	title: 'Design System/icons/LearnSomethingNewUntapped',
	component: LearnSomethingNewUntapped,
	argTypes: {
		color: { control: 'color' },
		rotate: { control: 'number' },
		width: {
			control: { type: 'number' },
		},
		height: {
			control: { type: 'number' },
		},
	},
} as ComponentMeta<typeof LearnSomethingNewUntapped>;

export const Default: ComponentStory<typeof LearnSomethingNewUntapped> = (
	args
) => <LearnSomethingNewUntapped {...args} />;
