// GENERATED BY ./scripts/storyBookScript.ts
import React from 'react';
import { ComponentStory, ComponentMeta } from '@storybook/react';
import { ArrowDown } from './ArrowDown';

export default {
	title: 'Design System/icons/ArrowDown',
	component: ArrowDown,
	argTypes: {
		color: { control: 'color' },
		rotate: { control: 'number' },
		width: {
			control: { type: 'number' },
		},
		height: {
			control: { type: 'number' },
		},
	},
} as ComponentMeta<typeof ArrowDown>;

export const Default: ComponentStory<typeof ArrowDown> = (args) => (
	<ArrowDown {...args} />
);
