// GENERATED BY ./scripts/storyBookScript.ts
import React from 'react';
import { ComponentStory, ComponentMeta } from '@storybook/react';
import { IconArrowLeft } from './IconArrowLeft';

export default {
	title: 'Design System/icons/IconArrowLeft',
	component: IconArrowLeft,
	argTypes: {
		color: { control: 'color' },
		rotate: { control: 'number' },
		width: {
			control: { type: 'number' },
		},
		height: {
			control: { type: 'number' },
		},
	},
} as ComponentMeta<typeof IconArrowLeft>;

export const Default: ComponentStory<typeof IconArrowLeft> = (args) => (
	<IconArrowLeft {...args} />
);
