// GENERATED BY ./scripts/storyBookScript.ts
import React from 'react';
import { ComponentStory, ComponentMeta } from '@storybook/react';
import { GetGoodRestTapped } from './GetGoodRestTapped';

export default {
	title: 'Design System/icons/GetGoodRestTapped',
	component: GetGoodRestTapped,
	argTypes: {
		color: { control: 'color' },
		rotate: { control: 'number' },
		width: {
			control: { type: 'number' },
		},
		height: {
			control: { type: 'number' },
		},
	},
} as ComponentMeta<typeof GetGoodRestTapped>;

export const Default: ComponentStory<typeof GetGoodRestTapped> = (args) => (
	<GetGoodRestTapped {...args} />
);
