// GENERATED BY ./scripts/storyBookScript.ts
import React from 'react';
import { ComponentStory, ComponentMeta } from '@storybook/react';
import { BeMindfulTapped } from './BeMindfulTapped';

export default {
	title: 'Design System/icons/BeMindfulTapped',
	component: BeMindfulTapped,
	argTypes: {
		color: { control: 'color' },
		rotate: { control: 'number' },
		width: {
			control: { type: 'number' },
		},
		height: {
			control: { type: 'number' },
		},
	},
} as ComponentMeta<typeof BeMindfulTapped>;

export const Default: ComponentStory<typeof BeMindfulTapped> = (args) => (
	<BeMindfulTapped {...args} />
);
