// GENERATED BY ./scripts/storyBookScript.ts
import React from 'react';
import { ComponentStory, ComponentMeta } from '@storybook/react';
import { UserSolid } from './UserSolid';

export default {
	title: 'Design System/icons/UserSolid',
	component: UserSolid,
	argTypes: {
		color: { control: 'color' },
		rotate: { control: 'number' },
		width: {
			control: { type: 'number' },
		},
		height: {
			control: { type: 'number' },
		},
	},
} as ComponentMeta<typeof UserSolid>;

export const Default: ComponentStory<typeof UserSolid> = (args) => (
	<UserSolid {...args} />
);
