// GENERATED BY ./scripts/storyBookScript.ts
import React from 'react';
import { ComponentStory, ComponentMeta } from '@storybook/react';
import { Users } from './Users';

export default {
	title: 'Design System/icons/Users',
	component: Users,
	argTypes: {
		color: { control: 'color' },
		rotate: { control: 'number' },
		width: {
			control: { type: 'number' },
		},
		height: {
			control: { type: 'number' },
		},
	},
} as ComponentMeta<typeof Users>;

export const Default: ComponentStory<typeof Users> = (args) => (
	<Users {...args} />
);
