// GENERATED BY ./scripts/storyBookScript.ts
import React from 'react';
import { ComponentStory, ComponentMeta } from '@storybook/react';
import { Subtract } from './Subtract';

export default {
	title: 'Design System/icons/Subtract',
	component: Subtract,
	argTypes: {
		color: { control: 'color' },
		rotate: { control: 'number' },
		width: {
			control: { type: 'number' },
		},
		height: {
			control: { type: 'number' },
		},
	},
} as ComponentMeta<typeof Subtract>;

export const Default: ComponentStory<typeof Subtract> = (args) => (
	<Subtract {...args} />
);
