// GENERATED BY ./scripts/storyBookScript.ts
import React from 'react';
import { ComponentStory, ComponentMeta } from '@storybook/react';
import { Close } from './Close';

export default {
	title: 'Design System/icons/Close',
	component: Close,
	argTypes: {
		color: { control: 'color' },
		rotate: { control: 'number' },
		width: {
			control: { type: 'number' },
		},
		height: {
			control: { type: 'number' },
		},
	},
} as ComponentMeta<typeof Close>;

export const Default: ComponentStory<typeof Close> = (args) => (
	<Close {...args} />
);
