// GENERATED BY ./scripts/storyBookScript.ts
import React from 'react';
import { ComponentStory, ComponentMeta } from '@storybook/react';
import { StayTrueToPurposeTapped } from './StayTrueToPurposeTapped';

export default {
	title: 'Design System/icons/StayTrueToPurposeTapped',
	component: StayTrueToPurposeTapped,
	argTypes: {
		color: { control: 'color' },
		rotate: { control: 'number' },
		width: {
			control: { type: 'number' },
		},
		height: {
			control: { type: 'number' },
		},
	},
} as ComponentMeta<typeof StayTrueToPurposeTapped>;

export const Default: ComponentStory<typeof StayTrueToPurposeTapped> = (
	args
) => <StayTrueToPurposeTapped {...args} />;
