// GENERATED BY ./scripts/storyBookScript.ts
import React from 'react';
import { ComponentStory, ComponentMeta } from '@storybook/react';
import { CheckboxSideCheck } from './CheckboxSideCheck';

export default {
	title: 'Design System/icons/CheckboxSideCheck',
	component: CheckboxSideCheck,
	argTypes: {
		color: { control: 'color' },
		rotate: { control: 'number' },
		width: {
			control: { type: 'number' },
		},
		height: {
			control: { type: 'number' },
		},
	},
} as ComponentMeta<typeof CheckboxSideCheck>;

export const Default: ComponentStory<typeof CheckboxSideCheck> = (args) => (
	<CheckboxSideCheck {...args} />
);
