// GENERATED BY ./scripts/storyBookScript.ts
import React from 'react';
import { ComponentStory, ComponentMeta } from '@storybook/react';
import { LogoSmall } from './LogoSmall';

export default {
	title: 'Design System/icons/LogoSmall',
	component: LogoSmall,
	argTypes: {
		color: { control: 'color' },
		rotate: { control: 'number' },
		width: {
			control: { type: 'number' },
		},
		height: {
			control: { type: 'number' },
		},
	},
} as ComponentMeta<typeof LogoSmall>;

export const Default: ComponentStory<typeof LogoSmall> = (args) => (
	<LogoSmall {...args} />
);
