// GENERATED BY ./scripts/storyBookScript.ts
import React from 'react';
import { ComponentStory, ComponentMeta } from '@storybook/react';
import { CloseOutlined } from './CloseOutlined';

export default {
	title: 'Design System/icons/CloseOutlined',
	component: CloseOutlined,
	argTypes: {
		color: { control: 'color' },
		rotate: { control: 'number' },
		width: {
			control: { type: 'number' },
		},
		height: {
			control: { type: 'number' },
		},
	},
} as ComponentMeta<typeof CloseOutlined>;

export const Default: ComponentStory<typeof CloseOutlined> = (args) => (
	<CloseOutlined {...args} />
);
