// GENERATED BY ./scripts/storyBookScript.ts
import React from 'react';
import { ComponentStory, ComponentMeta } from '@storybook/react';
import { UKCA } from './UKCA';

export default {
	title: 'Design System/icons/UKCA',
	component: UKCA,
	argTypes: {
		color: { control: 'color' },
		rotate: { control: 'number' },
		width: {
			control: { type: 'number' },
		},
		height: {
			control: { type: 'number' },
		},
	},
} as ComponentMeta<typeof UKCA>;

export const Default: ComponentStory<typeof UKCA> = (args) => (
	<UKCA {...args} />
);
