// GENERATED BY ./scripts/storyBookScript.ts
import React from 'react';
import { ComponentStory, ComponentMeta } from '@storybook/react';
import { AddUserOutlineSparkle } from './AddUserOutlineSparkle';

export default {
	title: 'Design System/icons/AddUserOutlineSparkle',
	component: AddUserOutlineSparkle,
	argTypes: {
		color: { control: 'color' },
		rotate: { control: 'number' },
		width: {
			control: { type: 'number' },
		},
		height: {
			control: { type: 'number' },
		},
	},
} as ComponentMeta<typeof AddUserOutlineSparkle>;

export const Default: ComponentStory<typeof AddUserOutlineSparkle> = (args) => (
	<AddUserOutlineSparkle {...args} />
);
