// GENERATED BY ./scripts/storyBookScript.ts
import React from 'react';
import { ComponentStory, ComponentMeta } from '@storybook/react';
import { AlertShieldSolid } from './AlertShieldSolid';

export default {
	title: 'Design System/icons/AlertShieldSolid',
	component: AlertShieldSolid,
	argTypes: {
		color: { control: 'color' },
		rotate: { control: 'number' },
		width: {
			control: { type: 'number' },
		},
		height: {
			control: { type: 'number' },
		},
	},
} as ComponentMeta<typeof AlertShieldSolid>;

export const Default: ComponentStory<typeof AlertShieldSolid> = (args) => (
	<AlertShieldSolid {...args} />
);
