// GENERATED BY ./scripts/storyBookScript.ts
import React from 'react';
import { ComponentStory, ComponentMeta } from '@storybook/react';
import { ArrowUp } from './ArrowUp';

export default {
	title: 'Design System/icons/ArrowUp',
	component: ArrowUp,
	argTypes: {
		color: { control: 'color' },
		rotate: { control: 'number' },
		width: {
			control: { type: 'number' },
		},
		height: {
			control: { type: 'number' },
		},
	},
} as ComponentMeta<typeof ArrowUp>;

export const Default: ComponentStory<typeof ArrowUp> = (args) => (
	<ArrowUp {...args} />
);
