// GENERATED BY ./scripts/storyBookScript.ts
import React from 'react';
import { ComponentStory, ComponentMeta } from '@storybook/react';
import { WarningSolid } from './WarningSolid';

export default {
	title: 'Design System/icons/WarningSolid',
	component: WarningSolid,
	argTypes: {
		color: { control: 'color' },
		rotate: { control: 'number' },
		width: {
			control: { type: 'number' },
		},
		height: {
			control: { type: 'number' },
		},
	},
} as ComponentMeta<typeof WarningSolid>;

export const Default: ComponentStory<typeof WarningSolid> = (args) => (
	<WarningSolid {...args} />
);
