// GENERATED BY ./scripts/storyBookScript.ts
import React from 'react';
import { ComponentStory, ComponentMeta } from '@storybook/react';
import { LeftPointerArrow } from './LeftPointerArrow';

export default {
	title: 'Design System/icons/LeftPointerArrow',
	component: LeftPointerArrow,
	argTypes: {
		color: { control: 'color' },
		rotate: { control: 'number' },
		width: {
			control: { type: 'number' },
		},
		height: {
			control: { type: 'number' },
		},
	},
} as ComponentMeta<typeof LeftPointerArrow>;

export const Default: ComponentStory<typeof LeftPointerArrow> = (args) => (
	<LeftPointerArrow {...args} />
);
