// GENERATED BY ./scripts/storyBookScript.ts
import React from 'react';
import { ComponentStory, ComponentMeta } from '@storybook/react';
import { CheckboxCheck } from './CheckboxCheck';

export default {
	title: 'Design System/icons/CheckboxCheck',
	component: CheckboxCheck,
	argTypes: {
		color: { control: 'color' },
		rotate: { control: 'number' },
		width: {
			control: { type: 'number' },
		},
		height: {
			control: { type: 'number' },
		},
	},
} as ComponentMeta<typeof CheckboxCheck>;

export const Default: ComponentStory<typeof CheckboxCheck> = (args) => (
	<CheckboxCheck {...args} />
);
