// GENERATED BY ./scripts/storyBookScript.ts
import React from 'react';
import { ComponentStory, ComponentMeta } from '@storybook/react';
import { MoveEveryDayLHQ } from './MoveEveryDayLHQ';

export default {
	title: 'Design System/icons/MoveEveryDayLHQ',
	component: MoveEveryDayLHQ,
	argTypes: {
		color: { control: 'color' },
		rotate: { control: 'number' },
		width: {
			control: { type: 'number' },
		},
		height: {
			control: { type: 'number' },
		},
	},
} as ComponentMeta<typeof MoveEveryDayLHQ>;

export const Default: ComponentStory<typeof MoveEveryDayLHQ> = (args) => (
	<MoveEveryDayLHQ {...args} />
);
