// GENERATED BY ./scripts/storyBookScript.ts
import React from 'react';
import { ComponentStory, ComponentMeta } from '@storybook/react';
import { CloseSolid } from './CloseSolid';

export default {
	title: 'Design System/icons/CloseSolid',
	component: CloseSolid,
	argTypes: {
		color: { control: 'color' },
		rotate: { control: 'number' },
		width: {
			control: { type: 'number' },
		},
		height: {
			control: { type: 'number' },
		},
	},
} as ComponentMeta<typeof CloseSolid>;

export const Default: ComponentStory<typeof CloseSolid> = (args) => (
	<CloseSolid {...args} />
);
