// GENERATED BY ./scripts/storyBookScript.ts
import React from 'react';
import { ComponentStory, ComponentMeta } from '@storybook/react';
import { PrintOutlined } from './PrintOutlined';

export default {
	title: 'Design System/icons/PrintOutlined',
	component: PrintOutlined,
	argTypes: {
		color: { control: 'color' },
		rotate: { control: 'number' },
		width: {
			control: { type: 'number' },
		},
		height: {
			control: { type: 'number' },
		},
	},
} as ComponentMeta<typeof PrintOutlined>;

export const Default: ComponentStory<typeof PrintOutlined> = (args) => (
	<PrintOutlined {...args} />
);
