// GENERATED BY ./scripts/storyBookScript.ts
import React from 'react';
import { ComponentStory, ComponentMeta } from '@storybook/react';
import { EyeOpenOutlined } from './EyeOpenOutlined';

export default {
	title: 'Design System/icons/EyeOpenOutlined',
	component: EyeOpenOutlined,
	argTypes: {
		color: { control: 'color' },
		rotate: { control: 'number' },
		width: {
			control: { type: 'number' },
		},
		height: {
			control: { type: 'number' },
		},
	},
} as ComponentMeta<typeof EyeOpenOutlined>;

export const Default: ComponentStory<typeof EyeOpenOutlined> = (args) => (
	<EyeOpenOutlined {...args} />
);
