// GENERATED BY ./scripts/storyBookScript.ts
import React from 'react';
import { ComponentStory, ComponentMeta } from '@storybook/react';
import { Indeterminate } from './Indeterminate';

export default {
	title: 'Design System/icons/Indeterminate',
	component: Indeterminate,
	argTypes: {
		color: { control: 'color' },
		rotate: { control: 'number' },
		width: {
			control: { type: 'number' },
		},
		height: {
			control: { type: 'number' },
		},
	},
} as ComponentMeta<typeof Indeterminate>;

export const Default: ComponentStory<typeof Indeterminate> = (args) => (
	<Indeterminate {...args} />
);
