// GENERATED BY ./scripts/storyBookScript.ts
import React from 'react';
import { ComponentStory, ComponentMeta } from '@storybook/react';
import { LearnSomethingNewTapped } from './LearnSomethingNewTapped';

export default {
	title: 'Design System/icons/LearnSomethingNewTapped',
	component: LearnSomethingNewTapped,
	argTypes: {
		color: { control: 'color' },
		rotate: { control: 'number' },
		width: {
			control: { type: 'number' },
		},
		height: {
			control: { type: 'number' },
		},
	},
} as ComponentMeta<typeof LearnSomethingNewTapped>;

export const Default: ComponentStory<typeof LearnSomethingNewTapped> = (
	args
) => <LearnSomethingNewTapped {...args} />;
