// GENERATED BY ./scripts/storyBookScript.ts
import React from 'react';
import { ComponentStory, ComponentMeta } from '@storybook/react';
import { Info } from './Info';

export default {
	title: 'Design System/icons/Info',
	component: Info,
	argTypes: {
		color: { control: 'color' },
		rotate: { control: 'number' },
		width: {
			control: { type: 'number' },
		},
		height: {
			control: { type: 'number' },
		},
	},
} as ComponentMeta<typeof Info>;

export const Default: ComponentStory<typeof Info> = (args) => (
	<Info {...args} />
);
