// GENERATED BY ./scripts/storyBookScript.ts
import React from 'react';
import { ComponentStory, ComponentMeta } from '@storybook/react';
import { EatGreenAndLeanTapped } from './EatGreenAndLeanTapped';

export default {
	title: 'Design System/icons/EatGreenAndLeanTapped',
	component: EatGreenAndLeanTapped,
	argTypes: {
		color: { control: 'color' },
		rotate: { control: 'number' },
		width: {
			control: { type: 'number' },
		},
		height: {
			control: { type: 'number' },
		},
	},
} as ComponentMeta<typeof EatGreenAndLeanTapped>;

export const Default: ComponentStory<typeof EatGreenAndLeanTapped> = (args) => (
	<EatGreenAndLeanTapped {...args} />
);
