// GENERATED BY ./scripts/storyBookScript.ts
import React from 'react';
import { ComponentStory, ComponentMeta } from '@storybook/react';
import { KeepHealthInCheckUntapped } from './KeepHealthInCheckUntapped';

export default {
	title: 'Design System/icons/KeepHealthInCheckUntapped',
	component: KeepHealthInCheckUntapped,
	argTypes: {
		color: { control: 'color' },
		rotate: { control: 'number' },
		width: {
			control: { type: 'number' },
		},
		height: {
			control: { type: 'number' },
		},
	},
} as ComponentMeta<typeof KeepHealthInCheckUntapped>;

export const Default: ComponentStory<typeof KeepHealthInCheckUntapped> = (
	args
) => <KeepHealthInCheckUntapped {...args} />;
