// GENERATED BY ./scripts/storyBookScript.ts
import React from 'react';
import { ComponentStory, ComponentMeta } from '@storybook/react';
import { AlertSolid } from './AlertSolid';

export default {
	title: 'Design System/icons/AlertSolid',
	component: AlertSolid,
	argTypes: {
		color: { control: 'color' },
		rotate: { control: 'number' },
		width: {
			control: { type: 'number' },
		},
		height: {
			control: { type: 'number' },
		},
	},
} as ComponentMeta<typeof AlertSolid>;

export const Default: ComponentStory<typeof AlertSolid> = (args) => (
	<AlertSolid {...args} />
);
