// GENERATED BY ./scripts/storyBookScript.ts
import React from 'react';
import { ComponentStory, ComponentMeta } from '@storybook/react';
import { KeepHealthInCheckLHQ } from './KeepHealthInCheckLHQ';

export default {
	title: 'Design System/icons/KeepHealthInCheckLHQ',
	component: KeepHealthInCheckLHQ,
	argTypes: {
		color: { control: 'color' },
		rotate: { control: 'number' },
		width: {
			control: { type: 'number' },
		},
		height: {
			control: { type: 'number' },
		},
	},
} as ComponentMeta<typeof KeepHealthInCheckLHQ>;

export const Default: ComponentStory<typeof KeepHealthInCheckLHQ> = (args) => (
	<KeepHealthInCheckLHQ {...args} />
);
